theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-relative-links

url: https://faq.blockception.dev

title: Blockdeption Developer FAQ
description: FAQ for blockceptions plugins, tools or more.

author:
  twitter: Blockception

exclude:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - README.md
  - Blockception-FAQ-Pages.code-workspace
  - LICENSE
  - Gemfile
  - Gemfile.lock

markdown: kramdown

kramdown:
  input: GFM

logo: https://images.squarespace-cdn.com/content/5bf1e11589c172ddd4394e7a/1543182314918-25XV95VZFAHOVTJU702A/bc_3D.png?format=1500w&content-type=image%2Fpng

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Blockception/FAQ-Pages" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
