theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-relative-links

url: https://faq.blockception.dev

title: Blockdeption Developer FAQ
description: FAQ for blockceptions plugins, tools or more.

author:
  twitter: Blockception

exclude:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - README.md
  - Blockception-FAQ-Pages.code-workspace
  - LICENSE
  - Gemfile
  - Gemfile.lock

markdown: kramdown

kramdown:
  input: GFM
