theme: jekyll-theme-slate
plugins:
  - jekyll-feed

title: Blockdeption Developer FAQ
description: FAQ for blockceptions plugins, tools or more.

author:
  twitter: Blockception

exclude:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - README.md
