baseURL = "faq.blockception.dev"
languageCode = "en-us"
title = "Blockception Developer FAQ"

theme = "ananke"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 0