baseURL = "http://faq.blockception.dev/"
languageCode = "en-us"
title = "Blockception - FAQ"
theme = "hugo-theme-techdoc"

[params]
  TableOfContents=true
  menu_style = "open_menu"
  
  # Source Code repository section
  github_repository = "https://github.com/Blockception/FAQ-Pages"
  version = "0.9.7"

  # Documentation repository section
  # documentation repository (set edit link to documentation repository)
  github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"

  # Analytic section
  google_analytics_id = "" # Your Google Analytics tracking id
  tag_manager_container_id = "" # Your Google Tag Manager container id
  google_site_verification = "" # Your Google Site Verification for Search Console

  # Open Graph and Twitter Cards settings section
  # Open Graph settings for each page are set on the front matter.
  # See https://gohugo.io/templates/internal/#open-graph
  # See https://gohugo.io/templates/internal/#twitter-cards
  title = "Hugo Techdoc Theme"
  images = ["images/og-image.png"] # Open graph images are placed in `static/images`

  # Theme settings section
  # Theme color
  # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
  custom_font_color = ""
  custom_background_color = ""

  # Date format
  dateformat = "" # default "2 Jan 2006"
  # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

  # path name excluded from documentation menu
  menu_exclusion = [
      "archives",
      "archive",
      "blog",
      "entry",
      "post",
      "posts",
  ]

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 0
        endLevel = 6
        ordered = true
    [markup.TableOfContents]
        startLevel = 0
        endLevel = 6
        ordered = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1