languageCode = "en-us"
title = "Blockception Developer FAQ"

theme = "docport"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 0

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"